image: "ruby:2.5.1"

rspec:
  cache:
    key: "${CI_COMMIT_REF_NAME}-1"
    paths:
      - vendor/bundle

  before_script:
    - bundle install --deployment --jobs=$(nproc) --without=development

  script:
    - bundle exec rspec

  tags:
    - ruby
