version: "3"

volumes:
  data:

services:
  web:
    command:
      - "--user"
      - "valeth:5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5"
    build:
      context: .
      args:
        build_target: "debug"
    volumes:
      - "data:/app/data"
    ports:
      - "9292:9292"
